carts/urls.py
from django.urls import path,include
from . import views

app_name="cart"
urlpatterns=[
    path('',views.cart_home,name='cart_home'),
    path('update/',views.cart_update,name='cart_update'),
    path('api/',views.cart_detail_api_view,name='cart-api'),
    path('get_entry/',views.get_entry,name='get-entry')
]

comments/urls.py
from django.urls import path,include
from . import views
app_name="comments"
urlpatterns=[

    path('reply/',views.reply_comment,name='reply_comment'),
    # path('api/',views.cart_detail_api_view,name='cart-api')
]

comments/models.py
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.db.models.signals import post_save
from django.urls import reverse
from django.utils import timezone


from accounts.models import Profile,User,Reciever
from notif.models import Notification
from products.models import Product
# Create your models here.

class CommentManager(models.Manager):
    def count(self):
        return "10"
    # def all(self):
    #     qs=super(CommentManager,self).filter(parent=None)
    #     return qs

class Comment(models.Model):
    author=models.ForeignKey(Profile,on_delete=models.CASCADE,related_name='comments',null=True)
    product=models.ForeignKey(Product,on_delete=models.CASCADE,null=True)
    text=models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    approved_comment = models.BooleanField(default=False)
    parent=models.ForeignKey("self",null=True,blank=True,on_delete=models.SET_NULL)
    comment_notif = GenericRelation(Notification, related_query_name='comments')
    objects=CommentManager()
    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        return self.product.get_absolute_url()

    def __str__(self):
        return self.text

    def children(self):
        return Comment.objects.filter(parent=self)

    @property
    def is_parent(self):
        if self.parent is not None:
            return False
        return True

def post_save_comment(sender,instance,created,*args,**kwargs):
    admin=Profile.objects.filter(user__admin=True).first()
    if created:
        reciever=Reciever()
        reciever.save()
        admin.Reciever=reciever
        # reciever.profile_set.add(admin.profile)
        admin.save()
        instance.comment_notif.create(reciver_s=reciever, actor=instance.author, verb='comment posted')


post_save.connect(post_save_comment, sender=Comment)

comments/forms.py
from django import forms
from .models import Comment
class commentForm(forms.Form):

    text=forms.CharField(widget=forms.Textarea())

comments/views.py
from django.shortcuts import render
from .models import Comment
# Create your views here.
def reply_comment(request):
    comment_id=request.POST.get('comment_id')
    if comment_id is not None:
        comment_obj=Comment.objects.get(id=comment_id)

comments/templates/comments/reply-comment.html
<form class="form-reply-comment-ajax" method="post" action="{% url 'comments:reply_comment' %}" data-endpoint="{% url 'comments:reply_comment' %}" class="form">
{% csrf_token %}
<input type="hidden" name="comment_id" value="{{ comment.id }}">

<span class="reply-span">
            <li>
											<div class="comment-img">
												<img src="img/comment/2.jpg" alt="" />
											</div>
											<div class="comment-info">
												<h4><a href="#">{{ comment.author.user.first_name }}</a></h4>
												<button class="reply pull-left btn btn-link" onclick="focusMethod()" type="submit">جواب دادن</button>
												<span>{{ comment.created_date }}</span>
												<p>{{ comment.text }}</p>
											</div>
										</li>
    </span>
</form>