accounts/urls.py
from django.conf.urls import url
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from . import views

app_name='accounts'

urlpatterns=[
    path('signup/', views.SignUp, name="signup"),
    path('google/', include('allauth.urls')),
    path('login/', views.loginView, name="login"),
    re_path(r'^login/(?P<confirmed>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.loginView, name="login"),
    path('logout/', auth_views.logout, name="logout"),
    path('signup_seller/', views.SignUpSeller, name="signup_seller"),
    # path('signup_seller2/', views.SignUpSeller2, name="signup_seller2"),
    path('validate_dikko_url/', views.validate_dikko_url, name='validate_dikko_url'),
    path('(?p<dikko_url>\w+)', include('profile_seller.urls'), name='seller_page'),
    url(r'^account_activation_sent/(?P<email>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})$',
        views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^password/change/$',
        auth_views.PasswordChangeView.as_view(),
        name='password_change'),
    url(r'^password/change/done/$',
        auth_views.PasswordChangeDoneView.as_view(),
        name='password_change_done'),

]

carts/urls.py
from django.urls import path,include
from . import views

app_name="cart"
urlpatterns=[
    path('',views.cart_home,name='cart_home'),
    path('update/',views.cart_update,name='cart_update'),
    path('api/',views.cart_detail_api_view,name='cart-api'),
    path('get_entry/',views.get_entry,name='get-entry')
]

accounts/models.py
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
from multiselectfield import MultiSelectField
 # from django.contrib.auth.models import User
from django.utils.functional import curry
from django.urls import reverse
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)

from products.models import Product

class State(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class City(models.Model):
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class UserManager(BaseUserManager):
    def create_user(self, email, password=None):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_staffuser(self, email, password):
        """
        Creates and saves a staff user with the given email and password.
        """
        user = self.create_user(
            email,
            password=password,
        )
        user.staff = True
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        """
        Creates and saves a superuser with the given email and password.
        """
        user = self.create_user(
            email,
            password=password,
        )
        user.staff = True
        user.admin = True
        user.save(using=self._db)
        return user

class User(AbstractBaseUser):
    date_joined = models.DateTimeField(('date joined'), default=timezone.now)
    # last_visit = models.DateTimeField(('last visit'))
    email=models.EmailField(verbose_name='email address',max_length=255,unique=True)
    first_name = models.CharField(max_length=35)
    last_name = models.CharField(max_length=45)
    # pro=models.ForeignKey('Profile',on_delete=models.CASCADE,related_name='user_profile',null=True)
    # active = models.BooleanField(default=True)
    is_active=models.BooleanField(default=False)
    staff = models.BooleanField(default=False)  # a admin user; non super-user
    admin = models.BooleanField(default=False)  # a superuser
    # notice the absence of a "Password field", that's built in.
    objects = UserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []  # Email & Password are required by default.

    def get_full_name(self):
        # The user is identified by their email address
        full_name=self.first_name+" "+self.last_name
        return full_name
    def get_short_name(self):
        # The user is identified by their email address
        return self.first_name

    def __str__(self):  # __unicode__ on Python 2
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        return self.staff

    @property
    def is_admin(self):
        "Is the user a admin member?"
        return self.admin

    # @property
    # def is_active(self):
    #     "Is the user active?"
    #     return self.active
class Reciever(models.Model):
    broadcast=models.BooleanField(default=False)


class Profile(models.Model):
    # first_name=models.CharField(max_length=25,blank=True)
    # last_name=models.CharField(max_length=35,blank=True)
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    is_seller=models.BooleanField(default=False)
    email_confirmed=models.BooleanField(default=False)
    # address=models.CharField(max_length=100,blank=True)
    # notification=models.ForeignKey(Notification,on_delete=models.SET_NULL,null=True,blank=True)
    state = models.CharField(max_length=30,blank=True,null=True)
    city = models.CharField(max_length=30,blank=True,null=True)
    phone_number=models.CharField(blank=True,max_length=10)
    national_code=models.CharField(max_length=10,blank=True)
    credit_card=models.CharField(max_length=16,blank=True)
    Reciever=models.ForeignKey(Reciever,on_delete=models.SET_NULL,blank=True,null=True)
    seller_profile=models.ForeignKey('Seller_Profile',models.SET_NULL,null=True,blank=True)


    def __str__(self):
        return self.user.email
class Address(models.Model):
    profile=models.ForeignKey(Profile,on_delete=models.CASCADE,null=True,blank=True)
    receiver_name=models.CharField(max_length=60,blank=False)
    receiver_phone_number=models.CharField(max_length=11,blank=False)
    state=models.CharField(max_length=30,blank=False)
    city=models.CharField(max_length=30,blank=False)
    postal_code=models.CharField(max_length=10)
    address=models.CharField(max_length=300)


def get_upload_path(instance, filename):
        return 'dikko/img/{0}/{1}'.format(instance.dikko_name, filename)
class Seller_Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,related_name='seller_profile')
    MY_CHOICES = (('صنایع دستی', 'صنایع دستی'),
                  ('محصولات کشاورزی', 'محصولات کشاورزی'),
                  ('محصولات فرهنگی', 'محصولات فرهنگی'),
                  ('پوشاک', 'پوشاک'),
                  ('محصولات غذایی', 'محصولات غذایی'),
                  ('عطاری', 'عطاری')
                  )

    # def get_absolute_url(self):
    #     return reverse(
    #         "profile_seller:seller_page",
    #         kwargs={
    #             "dikkourl": self.dikko_url,
    #         }
    #     )

    def __str__(self):
        return self.user.email


    # def save(self):
    #     im = Image.open(self.image)
    #     output = BytesIO()
    #     im = im.resize((679, 550))
    #     if im.mode in ("RGBA", "P"):
    #         im = im.convert("RGB")
    #     im.save(output, format='JPEG', quality=100)
    #     output.seek(0)
    #     self.image = InMemoryUploadedFile(output, 'ImageField', "%s.jpg" % self.image.name.split('.')[0], 'image/jpeg',
    #                                       sys.getsizeof(output), None)
    #     super(Seller_Profile, self).save()

accounts/forms.py
from django import forms
from django.contrib.auth import authenticate

from . import models
from django.db import transaction
from django.contrib.auth.forms import UserCreationForm
# from django.contrib.auth.models import User
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from .models import User
from django.core import validators
from django.core.exceptions import ValidationError
from multiselectfield import MultiSelectField
class UserForm_pro(forms.ModelForm):
    class Meta:
        model=models.User
        fields=('first_name','last_name')
        widgets={
            'first_name':forms.TextInput(attrs={'class':'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
        }
class UserForm(forms.ModelForm):
    # username = forms.CharField(label='Enter Username', min_length=4, max_length=150)
    email = forms.EmailField(label='Enter email',widget=forms.EmailInput(attrs={'class':'form-control'}))
    password1 = forms.CharField(label='Enter password', widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput(attrs={'class':'form-control'}))

    # birthdate=forms.DateField();
    # first_name=forms.CharField(max_length=25)
    # last_name=forms.CharField(max_length=35)
    CITY_1 = 'city_1'
    CITY_2 = 'city_2'
    CITY_CHOICES = (
        (CITY_1, u"City 1"),
        (CITY_2, u"City 2")
    )
    # cities = forms.MultipleChoiceField(choices=CITY_CHOICES)
    cities = MultiSelectField(choices=CITY_CHOICES)
    class Meta:
        model=models.Profile
        fields =( "email", "password1", "password2")
    # def clean_username(self):
    #     username = self.cleaned_data['username'].lower()
    #     r = User.objects.filter(username=username)
    #     if r.count():
    #         raise ValidationError("این نام کاربری قبلا وجود دارد")
    #     return username

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = User.objects.filter(email=email)
        if r.count():
            raise ValidationError("ایمیل وارد شده از قبل وجود دارد")
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise ValidationError("Password don't match")

        return password2




#
class SellerForm(forms.ModelForm):
    pass
#
#     class Meta:
#         model=models.Seller_Profile
#         fields = ("dikko_name","my_field","dikko_url","dikko_address","dikko_phone_number")
#         widgets = {
#             'dikko_address': forms.Textarea(attrs={'cols': 32, 'rows': 5}),
#             'dikko_name':forms.TextInput(attrs={'placeholder':'حاج علی'}),
#             'dikko_url':forms.TextInput(attrs={'placeholder':'alidikko'}),
#             'dikko_phone_number':forms.TextInput(attrs={'placeholder':'9378634654'})
#         }
#
#     def clean_dikko_name(self):
#         dikko_name=self.cleaned_data['dikko_name']
#         r=models.Seller_Profile.objects.filter(dikko_name=dikko_name)
#         if r.count():
#             raise ValidationError("نام دیکو از قبل وجود دارد")
#         return dikko_name
#
#     def clean_dikko_url(self):
#         dikko_url=self.cleaned_data['dikko_url'].lower()
#         print("clean")
#         print(dikko_url)
#         r=models.Seller_Profile.objects.filter(dikko_url=dikko_url)
#         print(r.count())
#         if r.count():
#             raise  ValidationError("این آدرس از قبل رزرو شده است")
#
#         return dikko_url
    # def __init__(self, *args, **kwargs):
    #     super(SellerForm, self).__init__(*args, **kwargs)
    #     self.fields['dikko_name'].help_text='sdfsdf'

class SellerForm2(forms.ModelForm):
    pass
#
#     class Meta:
#         model=models.Seller_Profile
#         fields = ("dikko_name","my_field","dikko_url","dikko_address","dikko_phone_number")
#
#
#     def clean_dikko_name(self):
#         dikko_name=self.cleaned_data['dikko_name']
#         r=models.Seller_Profile.objects.filter(dikko_name=dikko_name)
#         if r.count():
#             raise ValidationError("نام دیکو از قبل وجود دارد")
#         return dikko_name
#
#     def clean_dikko_url(self):
#         dikko_url=self.cleaned_data['dikko_url'].lower()
#         print("clean")
#         print(dikko_url)
#         r=models.Seller_Profile.objects.filter(dikko_url=dikko_url)
#         print(r.count())
#         if r.count():
#             raise  ValidationError("این آدرس از قبل رزرو شده است")
#
#         return dikko_url
#     # def __init__(self, *args, **kwargs):
#     #     super(SellerForm, self).__init__(*args, **kwargs)
#     #     self.fields['dikko_name'].help_text='sdfsdf'
#
#
class UserAdminCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""

    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email',)

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email','first_name','last_name', 'password', 'is_active', 'admin')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]

class LoginForm(forms.Form):
    email = forms.CharField(max_length=255, required=True,widget=forms.EmailInput(attrs={'class':'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}), required=True,)

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        try:
            user=authenticate(username=email, password=password)
            if not user.is_active:
                raise forms.ValidationError("متاسفیم! حساب کاربری فعال نشده است. لطفا به ایمیل خود مراجعه کنید")
        except:

            raise forms.ValidationError("متاسفیم! ایمیل یا کلمه عبور اشتباه وارد شده است")
        return self.cleaned_data

accounts/templates/accounts/account_activation_email.html
{% autoescape off %}
سلام {{ user.first_name }} عزیز

برای فعال سازی حساب خود لطفا به لینک زیر مراجعه کنید:

http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}
    با تشکر از عضویت شما
    بق بند
{% endautoescape %}

accounts/templates/accounts/account_activation_invalid.html
{% extends 'base.html' %}

{% block content %}
    <div class="account-area ptb-70 bg-2">
    <div class="container">
        <div class="row">
            <div class="col-lg-9 col-md-8 col-xs-12">
                <div class="ui-block">
                    <div class="ui-block-title">
                        <h4>لینک فعال سازی نامعتبر است. </h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>

{% endblock %}

accounts/templates/accounts/account_activation_sent.html
{% extends 'base.html' %}

{% block content %}
    <div class="account-area ptb-70 bg-2">
    <div class="container">
        <div class="row">
            <div class="col-lg-9 col-md-8 col-xs-12">
                <div class="ui-block">
                    <div class="ui-block-title">
                        <h3>{{ name }} عزیز</h3>
                        <br/>
                        <h4>ایمیل حاوی لینک فعال سازی به {{ email }} ارسال شد. لطفا ایمیل خود را چک کنید.</h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load socialaccount %}
{% block stylsheet %}

    <script src='https://www.google.com/recaptcha/api.js'></script>

{% endblock %}
{% block javascript %}
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{% static 'dikko/js/jquery.validate.js' %}"></script>
    <script src="{% static 'dikko/js/kamadatepicker.js' %}"></script>
    <script>
        kamaDatepicker('id_birth_date', {
            forceFarsiDigits: true
            , highlightSelectedDay: true
            , sync: true

        });

    </script>
    <script>

    </script>
    {#    <script>#}
    {#    $("#id_first_name,#id_last_name").keypress(function(event){#}
    {#    if(event.keyCode<1569 || event.keyCode>1741)#}
    {#        alert('your message');#}
    {##}
    {##}
    {##}
    {##}
    {#});#}
    {#    </script>#}
    <script>

        key = 10;
        jQuery.validator.addMethod("FarsiCheck", function (value, element) {
            console.log(value.charCodeAt(0));
            return this.optional(element) || ( (parseFloat(value.charCodeAt(0)) > 1569 ));
        }, "لطفا نام به فارسی وارد کنید");
        {#    $("#id_first_name,#id_last_name").keypress(function(event){#}
        {#        if(event.keyCode<1569 || event.keyCode>1741)#}
        {#            alert("لطفا نام و نام خانوادگی به فارسی وارد کنید")#}
        {#        console.log(key)#}
        {#    if(event.keyCode<1569 || event.keyCode>1741)#}
        {#        alert('your message');#}
        {##}
        {##}
        {##}
        {##}
        {#{);#}
        $().ready(function () {

            // validate signup form on keyup and submit
            $("#signupForm2").validate({
                rules: {
                    first_name: {
                        FarsiCheck: true,
                        required: true
                    },
                    last_name: {
                        FarsiCheck: true,
                        required: true,
                    },
                    username: {

                        required: true,
                        minlength: 4

                    },
                    password1: {
                        required: true,
                        minlength: 6
                    },
                    password2: {
                        required: true,
                        minlength: 6,
                        equalTo: "#id_password1"
                    },
                    email: {
                        required: true,
                        email: true
                    },

                },
                messages: {
                    first_name: {
                        FarsiCheck: "لطفا نام را به فارسی وارد کنید",
                        required: "لطفا نام خود را وارد کنید"
                    },

                    last_name: {
                        FarsiCheck: "لطفا نام خانوادگی را فارسی وارد کنید",
                        required: "لطفا نام خانوادگی خود را وارد کنید"
                    },
                    username: {
                        required: "لطفا نام کاربری خود را وارد کنید",
                        minlength: "حداقل طول مجاز نام کاربری 5 کارکاتر است"

                    },
                    password1: {
                        required: "لطفا پسورد خود را وارد کنید",
                        minlength: "حداقل طول مجاز پسورد 6 کاراکتر است"
                    },
                    password2: {
                        required: "لطفا پسورد خود را دوباره وارد کنید",
                        minlength: "حداقل طول مجاز پسورد 6 کاراکتر است",
                        equalTo: "لطفا پسوردی مشابه بالا وارد کنید"
                    },
                    email: "لطفا ایمیل معتبر وارد کنید",

                }
            });
            // propose username by combining first- and lastname
            {#		$("#email").focus(function() {#}
            {#			var firstname = $("#firstname").val();#}
            {#			var lastname = $("#lastname").val();#}
            {#			if (firstname && lastname && !this.value) {#}
            {#				this.value = firstname + "." + lastname;#}
            {#			}#}
            {#		});#}


        });
    </script>
{% endblock %}
{% block content %}

    <div class="account-area ptb-70 bg-2">
        <div class="container">
            {#				<div class="row">#}

            <div class="col-md-6 col-md-offset-3  col-xs-12">
                <h3 class="sidebar-title"> ثبت نام در بق بند</h3>

                <div class="checkout-form">


                    <form method="post" id="signupForm2" action="">
{#                        <h5>حساب گوگل دارید؟ </h5>#}
{#                        <br>#}
{#                        <a href="{% provider_login_url 'google' %}">ثبت نام با حساب گوگل</a>#}
{#                        <br>#}

                        {% csrf_token %}
                        {% if user_form.errors %}
                            {% for field in user_form %}
                                {% for error in field.errors %}
                                    <div class="alert alert-danger">
                                        <strong>{{ error|escape }}</strong>
                                    </div>
                                {% endfor %}
                            {% endfor %}
                            {% for error in user_form.non_field_errors %}
                                <div class="alert alert-danger">
                                    <strong>{{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                        {% endif %}

                        <div class="row">
                            <div class="col-xs-12">
                                <span>آدرس ایمیل <span class="star">*</span></span>
                                {{ user_form.email }}

                            </div>
                            <div class="col-xs-12">
                                <span>نام <span class="star">*</span></span>

                                {{ user_form_pro.first_name }}
                            </div>
                            <div class="col-xs-12">
                                <span>نام خانوادگی <span class="star">*</span></span>

                                {{ user_form_pro.last_name }}
                            </div>
                            {#									<div class="col-xs-12">#}
                            {#										<span>نام کاربری <span class="star">*</span></span>#}
                            {##}
                            {#                                        {{user_form.username }}#}
                            {#									</div>#}
                            <div class="col-xs-12">
                                <span>پسورد <span class="star">*</span></span>

                                {{ user_form.password1 }}
                            </div>
                            <div class="col-xs-12">
                                <span>دوباره نویسی پسورد <span class="star">*</span></span>

                                {{ user_form.password2 }}
                            </div>

                            {#                                    <div class="col-xs-12">#}
                            {#										<span>تولد <span class="star">*</span></span>#}
                            {##}
                            {#                                        {{user_form.birth_date }}#}
                            {#									</div>#}
                            {#                                     <script src='https://www.google.com/recaptcha/api.js'></script>#}
                            {##}
                            {#                                    <div class="col-xs-12">#}
                            {#                                      <div class="g-recaptcha" data-sitekey="6Lcr6XIUAAAAAOTdySszwWYFHlnf4pX00hlvZc2J"></div>#}
                            {#                                    </div>#}
                            <div class="col-xs-12">
                                {#										<button type="submit">ثبت نام</button>#}
                                <button type="submit"
                                        class="g-recaptcha"
                                        data-sitekey="6LfTFocUAAAAAFLAZwRSDxdrXkZBUMzWQpBXDmcx"
                                        data-callback="YourOnSubmitFn">
                                    ثبت نام
                                </button>
                            </div>

                        </div>

                    </form>


                </div>
            </div>
            {#				</div>#}
        </div>
    </div>

    <!-- newsletter-area start -->
{% endblock %}

accounts/templates/accounts/signup_seller2.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block javascript %}
{#     <script src="{% static 'dikko/js/jquery.validate.js' %}"></script>#}
{#    <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>#}
{#	<script src="http://netdna.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>#}
{#    <script>#}
{#console.log("hggghjjj");#}
{#    sw=0;#}
{#    jQuery.validator.addMethod("FarsiCheck2", function(value, element) {#}
{#        console.log("hggghjjj");#}
{#        $("#id_dikko_url").change(function () {#}
{#            var dikko_url = $(this).val();#}
{#            console.log($(this).val());#}
{#            $.ajax({#}
{#                url: '/accounts/validate_dikko_url/',#}
{#                data: {#}
{#                    'dikko_url': dikko_url#}
{#                },#}
{#                dataType: 'json',#}
{#                success: function (data) {#}
{#                    if (data.is_taken) {#}
{#                        alert("این آدرس از قبل رزرو شده است");#}
{#                        $("id_dikko_url").helptext("Sdsd");#}
{#                        sw = 1;#}
{#                    }#}
{#                }#}
{#            });#}
{##}
{#        });#}
{#        return this.optional(element) || ( sw > 0);#}
{#    }, "این نام گرفته شده است");#}
{##}
{#    	$().ready(function() {#}
{##}
{#		// validate signup form on keyup and submit#}
{#		$("#signup_seller").validate({#}
{#			rules: {#}
{#			    dikko_url:{#}
{#			        FarsiCheck2:true,#}
{#                }#}
{##}
{#			},#}
{#			messages: {#}
{#                dikko_url:{#}
{#                    FarsiCheck2:"kjkhkhkkh",#}
{#                }#}
{##}
{#			}#}
{#		});#}
{#		// propose username by combining first- and lastname#}
{#		$("#email").focus(function() {#}
{#			var firstname = $("#firstname").val();#}
{#			var lastname = $("#lastname").val();#}
{#			if (firstname && lastname && !this.value) {#}
{#				this.value = firstname + "." + lastname;#}
{#			}#}
{#		});#}
{##}
{##}
{#	});#}


{#  </script>#}
{% endblock %}
{% block content %}

		<div class="account-area ptb-70 bg-2">
			<div class="container">
				<div class="row">

					<div class="col-md-12 col-sm-6 col-xs-12 ">

                        {% if user.is_authenticated %}

                             <h3 class="sidebar-title">فروشنده شوید</h3>
                        {% endif %}
						<div class="checkout-form">
							<form method="post">
                                {% csrf_token %}
                            {% if seller_form.errors %}
    {% for field in seller_form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in seller_form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

								<div class="row justify-content-start">
                                    {% if  user.is_authenticated %}


                                        <div class="col-xs-3">
										<span>آدرس تولیدی خود را وارد کنید<span class="star">*</span></span>


									</div>
                                        <div class="col-xs-3 col-xs-offset-8" >
                                        {{ seller_form.dikko_address }}
                                        </div>



								</div>
                                        <div class="row">
                                        <div class="col-xs-3">
                                           <span>شماره تماس خود را وارد کنید<span class="star">*</span></span>
                                        </div>
                                        <div class="col-xs-3 col-xs-offset-8" >
                                        {{ seller_form.dikko_phone_number }}
                                        </div>
                                        </div>
                                         <div class="row">
{#                                        <div class="col-xs-3">#}
{#                                           <span>آدرس اختصاصی دیکو خود را انتخاب کنید<span class="star">*</span></span>#}
{#                                        </div>#}
{#                                        <div class="col-xs-3 col-xs-offset-8"  >#}
{#                                        {{ seller_form.dikko_url }}#}
{#                                        </div>#}
{#                                        </div>#}
                                        <div class="col-xs-12">
										<button type="submit">ثبت اطلاعات</button>
									</div>
                                {% endif %}
							</form>
						</div>
					</div>


			</div>
		</div>
        </div>
		<!-- newsletter-area start -->
{% endblock %}

accounts/templates/accounts/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
   
</head>
<body>
سلام {{name}}
</body>
</html>