carts/urls.py
from django.urls import path,include
from . import views

app_name="cart"
urlpatterns=[
    path('',views.cart_home,name='cart_home'),
    path('update/',views.cart_update,name='cart_update'),
    path('api/',views.cart_detail_api_view,name='cart-api'),
    path('get_entry/',views.get_entry,name='get-entry')
]

dashboard/urls.py
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from . import views
from discount_codes import views as discount_views
from favorite_list import views as favorite_views
from analytics import views as analytics_views
from subscribers import views as subscribers_views
from complaints import views as complain_views
app_name='dashboard'


urlpatterns=[
    path('',views.dashboard_account_information,name='dashboard_account_information'),
    path('addresses/', views.Address_List.as_view(), name='dashboard_addresses'),
    path('dikko_management/create_address',views.address_create,name='dashboard_address_create'),
    re_path('dikko_management/remove_address/(?P<pk>\d+)/$',views.Address_Delete.as_view(),name='dashboard_address_remove'),
    re_path('dikko_management/edit_address/(?P<pk>\d+)/$',views.Address_Update.as_view(),name='dashboard_address_edit'),
    re_path('dikko_management/edit_address/(?P<pk>\d+)/(?P<return>[\w-]+)$',views.Address_Update.as_view(),name='dashboard_address_edit'),
    path('dikko_management/',views.dashboard_dikko_management.as_view(),name='dashboard_dikko_management'),
    re_path(r'dikko_info/details/(?P<pk>\d+)/$',views.Dikko_Info_Details.as_view(),name='dashboard_dikko_info_details'),
    path('dikko_info/',views.Dikko_Info_List.as_view(),name='dashboard_dikko_info'),
    path('create_dikko/',views.Create_dikko.as_view(),name='dashboard_create_dikko'),
    re_path('dikko_management/remove/products_list/(?P<pk>\d+)/$',views.Dikko_Products_List.as_view(),name='dashboard_dikko_products_list_remove'),
    re_path('dikko_management/edit/products_list/(?P<pk>\d+)/$',views.Dikko_Products_List.as_view(),name='dashboard_dikko_products_list_edit'),
    path('dikko_management/pre_add',views.Dikko_Info_List.as_view(),name='dashboard_dikko_pre_add'),
    path('dikko_management/pre_remove',views.Dikko_Info_List.as_view(),name='dashboard_dikko_pre_remove'),
    path('dikko_management/pre_edit',views.Dikko_Info_List.as_view(),name='dashboard_dikko_pre_edit'),
    re_path(r'dikko_management/add_product/(?P<pk>\d+)/$',views.Dikko_Add_Product.as_view(),name='dashboard_dikko_management_add_product'),
    re_path(r'dikko_management/edit_product/(?P<pk>\d+)/(?P<pro>\d+)$',views.Dikko_Edit_Product,name='dashboard_dikko_management_edit_product'),
    re_path(r'dikko_management/remove_product/(?P<pk>\d+)/(?P<pro>\d+)$',views.Dikko_Remove_Product.as_view(),name='dashboard_dikko_management_remove_product'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),
    path('ajax/load-fields/', views.load_fields, name='ajax_load_fields'),
    path('orders/',views.dashboard_orders.as_view(),name='dashboard_orders'),
    path('notifications/create', views.create_notification, name='dashboard_notifications_create'),
    path('notifications/list', views.Notifications_List.as_view(), name='dashboard_notifications_list'),
    path('notifications/orders',views.notifications_orders_list,name='dashboard_notifications_orders'),
    path('notifications/comments',views.notifications_comments_list,name='dashboard_notifications_comments'),
    re_path(r'^notifications/orders/details/(?P<pk>\d+)/$',views.notifications_orders_details.as_view(),name='dashboard_notifications_orders_details'),
    path('dicount_codes/',discount_views.Create_Code.as_view(),name='dashboard_discount_codes'),
    path('favorite_list/',favorite_views.Favorite_List.as_view(),name='dashboard_favorite_list'),
    path('analytics/',analytics_views.home.as_view(),name='dashboard_analytics'),
    path('analytics/sell_per_product',analytics_views.sell_per_product,name='dashboard_analytics_sell_per_product'),
    path('analytics/sell_per_dikko', analytics_views.sell_per_dikko, name='dashboard_analytics_sell_per_dikko'),
    path('subscribers/', subscribers_views.communityList, name='dashboard_subscribers_communities'),
    re_path(r'^subscribers/community/(?P<slug>[\w-]+)/create_message/$', subscribers_views.createMessage, name='dashboard_subscribers_create_message'),
    re_path(r'^subscribers/community/(?P<slug>[\w-]+)/message_list/$', subscribers_views.messagesList, name='dashboard_subscribers_message_list'),
    re_path(r'^subscribers/community/(?P<slug>[\w-]+)/message_details/(?P<message>[\w-]+)$', subscribers_views.messageDetail, name='dashboard_subscribers_message_details'),
    path('complains/', complain_views.complainList, name='dashboard_complains_list'),
]

payment/urls.py
from django.urls import path
from .views import home,result
app_name="payment"
urlpatterns=[
    path('',home,name='home'),
    path('result/',result,name='result')
]

payment/models.py
from django.db import models
from django.utils import timezone

from orders.models import Order
# Create your models here.

class Payment(models.Model):
    order=models.ForeignKey(Order,on_delete=models.SET_NULL,null=True)
    trans_id=models.CharField(max_length=50)
    trace_num=models.CharField(max_length=15,null=True)
    reference_num=models.CharField(max_length=15,null=True)
    action=models.CharField(max_length=10,null=True)
    code=models.IntegerField()
    created_date=models.DateTimeField()
    modified_date=models.DateTimeField()

    def __str__(self):
        return self.order.order_id
    def save(self, *args, **kwargs):
        ''' On save, update timestamps '''
        if not self.id:
            self.created_date = timezone.localtime(timezone.now())
        self.modified_date=timezone.localtime(timezone.now())

        return super(Payment, self).save(*args, **kwargs)

payment/views.py
import datetime
import requests
from jalali_date import datetime2jalali
from django.shortcuts import render
from orders.models import Order
from .models import Payment
from django.views.decorators.csrf import csrf_exempt
from Cryptodome.PublicKey import RSA
from base64 import b64encode
from django.conf import settings
from . import rsa
from carts.models import Cart
from xml.dom import minidom
# Create your views here.
def home(request):
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    if Order.objects.filter(cart=cart_obj).exists():
        order=Order.objects.get(cart=cart_obj)
        if order.status=='اولیه': ### jologiri az pardakht sefaresh tekrari
            merchantCode=4500268
            terminalCode=1681935
            amount=int(order.total)*10
            callback_uri='https://boghband.com/payment/result/'
            timeStamp=datetime.datetime.now().strftime('%y/%m/%d %H:%M:%S')
            invoiceNumber=order.order_id
            # invoiceDate="2019/02/28 13:11:33"
            indate=datetime.datetime.now()
            invoiceDate=datetime2jalali(indate).strftime('%y/%m/%d %H:%M:%S')
            action="1003"
            data="#"+str(merchantCode)+"#"+str(terminalCode)+"#"+str(invoiceNumber)+"#"+str(invoiceDate)+"#"+str(amount)+"#"+str(callback_uri)+"#"+str(action)+"#"+str(timeStamp)+"#"
            dir=settings.BASE_DIR+"/payment/private2.pem"
            key=open(dir, "r").read()
            private=RSA.importKey(key)

            signature=b64encode(rsa.sign(bytes(data, 'utf-8'), private, "SHA-1"))
            sign=signature.decode("utf-8")
            order.invoiceDate=indate
            order.save()

            # if request.POST:
            #     print(request.POST)
            #     payMethod=request.POST.get('payMethod')
            #     if payMethod=='1':## online payment choose
            #         r=requests.post('http://127.0.0.1:8000/payment/result/' ,data={'kir':5})
            #         print(r.status_code)
                    # wsdl='http://api.nextpay.org/gateway/token.wsdl'
                    # client=zeep.Client(wsdl=wsdl)
                    # amount=int(order.total)
                    # api_key='7564be43-5660-4d79-9192-ae6358a5a0b5'
                    # token_obj=client.service.TokenGenerator(api_key=api_key,
                    #                                         order_id=order.order_id,
                    #                                         amount=amount,
                    #                                         callback_uri='http://127.0.0.1:8000/payment/result/')
                    # trans_id=token_obj.trans_id
                    # code=token_obj.code
                    # payment=Payment(order=order,trans_id=trans_id,code=code)
                    # payment.save()
                    # if code == -1:
                    #     url='http://api.nextpay.org/gateway/payment/'+trans_id
                    #     return redirect(url)


    #     print(order)
    #
    #     wsdl='http://api.nextpay.org/gateway/token.wsdl'
    #     client=zeep.Client(wsdl=wsdl)
    #     amount=int(order.total)
    #     print(amount)
    #     api_key='7564be43-5660-4d79-9192-ae6358a5a0b5'
    #     params={'api_key':api_key,'order_id':'NS4JINQ87F','amount':22000,'callback_uri':'http://127.0.0.1:8000/payment/callback/'}
    #     print("sdsdscsdc")
    #     token_obj=client.service.TokenGenerator(api_key='7564be43-5660-4d79-9192-ae6358a5a0b5',
    #                                         order_id=order.order_id,
    #                                         amount=amount,
    #                                         callback_uri='http://127.0.0.1:8000/payment/callback/')
    #     print(token_obj)
    #     trans_id=token_obj.trans_id
    #     code=token_obj.code
    #     print(trans_id)
    #     print(code)
    #     if code == -1:
    #         url='http://api.nextpay.org/gateway/payment/'+trans_id
    #         return redirect(url)


            return render(request,"payment/payment.html",{"cart_obj":cart_obj,"order":order,"merchantCode":merchantCode
                                                          ,"terminalCode":terminalCode,"invoiceNumber":invoiceNumber,
                                                          "invoiceDate":invoiceDate,"amount":amount,
                                                          "redirectAddress":callback_uri,"action":action,"timeStamp":timeStamp,
                                                          "sign":sign})
    # else:
    #     print("invalid")
@csrf_exempt
def result(request):

    # return render(request, 'payment/result.html', {"valid": 1})
    InvoiceNumber=request.GET.get('iN')
    InvoiceDate=request.GET.get('iD')
    TransactionReferenceID=request.GET.get('tref')
    url='https://pep.shaparak.ir/CheckTransactionResult.aspx'

    postdata={
        'invoiceUID':TransactionReferenceID,
    }

    r=requests.post(url, data=postdata)
    print(r.status_code)
    print(r.text)
    xmldoc=minidom.parseString(r.text)
    amount=xmldoc.getElementsByTagName('amount')[0].firstChild.data
    order_id=xmldoc.getElementsByTagName('invoiceNumber')[0].firstChild.data
    merchantCode=xmldoc.getElementsByTagName('merchantCode')[0].firstChild.data
    terminalCode=xmldoc.getElementsByTagName('terminalCode')[0].firstChild.data
    trans_id=xmldoc.getElementsByTagName('transactionReferenceID')[0].firstChild.data
    result=xmldoc.getElementsByTagName('result')[0].firstChild.data
    action=xmldoc.getElementsByTagName('action')[0].firstChild.data
    trace_num=xmldoc.getElementsByTagName('traceNumber')[0].firstChild.data
    reference_num=xmldoc.getElementsByTagName('referenceNumber')[0].firstChild.data
    # for a in amount:
    print(amount)
    print(merchantCode)
    print(order_id)
    print(terminalCode)
    if result=='True':
        if trans_id==TransactionReferenceID and order_id==InvoiceNumber:
            if Order.objects.filter(order_id=order_id).exists():
                order_obj=Order.objects.get(order_id=order_id)
                if order_obj.status== 'اولیه':
                    indate=order_obj.invoiceDate
                    invoiceDate=datetime2jalali(indate).strftime('%y/%m/%d %H:%M:%S')
                    timeStamp=datetime.datetime.now().strftime('%y/%m/%d %H:%M:%S')
                    data="#"+str(merchantCode)+"#"+str(terminalCode)+"#"+str(InvoiceNumber)+"#"\
                         +str(invoiceDate)+"#"+str(amount)+"#"+str(timeStamp)+"#"
                    dir=settings.BASE_DIR+"/payment/private2.pem"
                    key=open(dir, "r").read()
                    private=RSA.importKey(key)

                    signature=b64encode(rsa.sign(bytes(data, 'utf-8'), private, "SHA-1"))
                    sign=signature.decode("utf-8")
                    url='https://pep.shaparak.ir/VerifyPayment.aspx'
                    # ... your code ...

                    postdata={
                        'InvoiceNumber': InvoiceNumber,
                        'InvoiceDate':InvoiceDate,
                        'MerchantCode':merchantCode,
                        'TerminalCode':terminalCode,
                        'Amount':amount,
                        'TimeStamp':timeStamp,
                        'Sign':sign

                    }

                    r=requests.post(url, data=postdata)
                    print(r.status_code)
                    print(r.text)
                    xmldoc=minidom.parseString(r.text)
                    result=xmldoc.getElementsByTagName('result')[0].firstChild.data
                    print(result)
                    if result=='True':
                        order_obj.status='پرداخت شده'
                        order_obj.save()
                        payment=Payment(trans_id=trans_id,code=0,order=order_obj,action=action,
                                        trace_num=trace_num,reference_num=reference_num)
                        payment.save()


                        cart_obj=Cart.objects.new(request.user)
                        request.session['cart_id']=cart_obj.id
                        request.session['cart_items_count']=0
                        return render(request, 'payment/result.html', {"valid": 1, "order": order_obj})
                    else:
                        return render(request, 'payment/result.html', {"valid": 0, "order": order_obj})

    else:
        if Order.objects.filter(order_id=order_id).exists():
            order_obj=Order.objects.get(order_id=order_id)
            print("Not successfull")
            return render(request, 'payment/result.html', {"valid": 0,"order": order_obj})




    #     order_id=request.POST.get('order_id')
    #     trans_id=request.POST.get('trans_id')
    #     if Order.objects.filter(order_id=order_id).exists() and Payment.objects.filter(trans_id=trans_id).exists():
    #         order_obj=Order.objects.get(order_id=order_id)
    #         payment_obj=Payment.objects.get(trans_id=trans_id)
    #         if order_obj.status=='اولیه':
    #             wsdl='http://api.nextpay.org/gateway/token.wsdl'
    #             client=zeep.Client(wsdl=wsdl)
    #             amount=int(order_obj.total)
    #             token_obj=client.service.PaymentVerification(api_key='7564be43-5660-4d79-9192-ae6358a5a0b5',
    #                                                          order_id=order_id,
    #                                                          amount=amount,
    #                                                          trans_id=trans_id)
    #             if token_obj.code==0:
    #                 order_obj.status='پرداخت شده'
    #                 order_obj.save()
    #                 payment_obj.code=token_obj.code
    #                 payment_obj.save()
    #                 return render(request, 'payment/result.html', {"valid":1,"order":order_obj})
    #
    #             else:
    #                 payment_obj.code=token_obj.code

payment/templates/payment/result.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load filter_numbers %}
{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'shipping/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'carts/css/timeline.css' %}">
    <link rel="stylesheet" href="{% static 'carts/css/cart.css' %}">
{% endblock %}
{% block content %}
    <section>

        <nav style="direction: ltr">
            <ol class="cd-multi-steps text-top">
                <li class="current"><em>تایید و ارسال</em></li>
                <li><em>پرداخت</em></li>
                <li><em>اطلاعات آدرس</em></li>
                <li><em>سبد خرید</em></li>

            </ol>
        </nav>
    </section>

    <!-- checkout-area start -->
    <div class="checkout-area ptb-70 bg-2">
        <div class="container">
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li class="{{ message.tags }}">{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}


            <div class="row">

                    <div class="col-md-12 col-sx-12">
                        <div class="shopping-cart">
                            <div class="title">نتیجه عملیات پرداخت</div>
                            <div class="checkout-form">
                             {% if valid == 1 %}
                                <h3>پرداخت شما با موفقیت انجام شد.</h3>
                                 <br>
                                 <h4>سفارش شما در انتظار تایید بق بند است.</h4>
                                 <br>

                                 <h4> میتوانید وضعیت سفارش خود را از طریق  <a href="{% url 'dashboard:dashboard_orders' %}">حساب کاربری</a> خود مشاهده و یا منتظر دریافت ایمیل از طرف بق بند باشید</h4>
                                {% else %}
                                 <h3>متاسفانه مشکلی در پرداخت شما بوجود آمده است.</h3>
                                 <br>
                                 <h4>در صورت کسر وجه از حساب شما مبلغ کسر شده ظرف 48 ساعت آینده به حساب شما باز خواهد گشت</h4>
                                {% endif %}
                            <br>
                            <h4 style="text-align: center">کدپیگیری شما:</h4><h2 style="text-align: center">{{ order.order_id }}</h2>
                            </div>
                        </div>

                    </div>



            </div>
            {#            <div class="row">#}
            {#                <div class="col-md-offset-8">#}
            {#                    <div class="checkout-form-wrap mb-20">#}
            {#                        <h3 class="checkout-title">استفاده از کد تخفیف</h3>#}
            {#                        <div class="checkout-form">#}
            {#                            <form method="post" id="discount_form">#}
            {#                                <input type="hidden" name="cart_id" value="{{ cart_obj.pk }}">#}
            {#                                <input type="text" name="discount_code"#}
            {#                                       placeholder="اگر کد تخفیف دارید اینجا وارد کنید"/>#}
            {#                                <button type="submit" >اعمال کد تخفیف#}
            {#                                </button>#}
            {##}
            {#                            </form>#}
            {#                        </div>#}
            {#                    </div>#}
            {#                </div>#}
            {#            </div>#}


        </div>
    </div>
    {#    </div>#}
{% endblock %}

{% block javascript %}
    {#    <script src="{% static 'dikko/js/jquery.validate.js' %}"></script>#}
    <script>

        $(document).ready(function () {
            {#    var modal = $('#discount_modal');#}
            {#    var val;#}
            {#    var old;#}
            {#    var reload=false#}
            {#     total = $(".total");#}
            {#    var discountform = $("#discount_form");#}
            {#    discountform.submit(function (event) {#}
            {#        console.log("hii")#}
            {#        event.preventDefault();#}
            {#        var thisForm = $(this);#}
            {#        var formData = thisForm.serialize();#}
            {#        console.log(formData)#}
            {#        $.ajax({#}
            {#            url: "/discount_codes/",#}
            {#            method: "Get",#}
            {#            data: formData,#}
            {#            success: function (data) {#}
            {##}
            {#                if (data.valid === 0) {#}
            {#                    console.log("sdcsssssssssssssssssssssssss")#}
            {##}
            {#                     swal("کاربر عزیز", data.message, "error");#}
            {##}
            {#                }#}
            {#                else {#}
            {#                    console.log("vvvvvvvvvvvv")#}
            {#                    val=data.total.replace("\"", '');#}
            {#                    old=data.old_total.replace("\"", '');#}
            {#                    reload=true;#}
            {##}
            {##}
            {##}
            {# modal.modal('show');#}
            {#modal.find('.modal-title').text('تبریک')#}
            {#modal.find('.modal-body').html("<p>کد تخفیف با موفقیت اعمال شد. میزان تخفیف: "+data.gain+"</P>")#}
            {#                    swal("کاربر عزیز", "کد تخفیف با موفقیت اعمال شد. میزان تخفیف"+data.gain, "success");#}
            {#                     location.reload(true);#}
            {##}
            {#                           console.log(last)#}
            {#                }#}
            {##}
            {#            }#}
            {#        })#}
            {##}
            {##}
            {#    });#}
            {#    $('.swal-button').click(function () {#}
            {#         console.log("closeeeee")#}
            {#    })#}
            {##}
            {##}
            {##}
            {##}
        });


        // validate signup form on keyup and submit

    </script>
{% endblock %}