carts/urls.py
from django.urls import path,include
from . import views

app_name="cart"
urlpatterns=[
    path('',views.cart_home,name='cart_home'),
    path('update/',views.cart_update,name='cart_update'),
    path('api/',views.cart_detail_api_view,name='cart-api'),
    path('get_entry/',views.get_entry,name='get-entry')
]

dashboard/urls.py
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from . import views
from discount_codes import views as discount_views
from favorite_list import views as favorite_views
from analytics import views as analytics_views
from subscribers import views as subscribers_views
from complaints import views as complain_views
app_name='dashboard'


urlpatterns=[
    path('',views.dashboard_account_information,name='dashboard_account_information'),
    path('addresses/', views.Address_List.as_view(), name='dashboard_addresses'),
    path('dikko_management/create_address',views.address_create,name='dashboard_address_create'),
    re_path('dikko_management/remove_address/(?P<pk>\d+)/$',views.Address_Delete.as_view(),name='dashboard_address_remove'),
    re_path('dikko_management/edit_address/(?P<pk>\d+)/$',views.Address_Update.as_view(),name='dashboard_address_edit'),
    re_path('dikko_management/edit_address/(?P<pk>\d+)/(?P<return>[\w-]+)$',views.Address_Update.as_view(),name='dashboard_address_edit'),
    path('dikko_management/',views.dashboard_dikko_management.as_view(),name='dashboard_dikko_management'),
    re_path(r'dikko_info/details/(?P<pk>\d+)/$',views.Dikko_Info_Details.as_view(),name='dashboard_dikko_info_details'),
    path('dikko_info/',views.Dikko_Info_List.as_view(),name='dashboard_dikko_info'),
    path('create_dikko/',views.Create_dikko.as_view(),name='dashboard_create_dikko'),
    re_path('dikko_management/remove/products_list/(?P<pk>\d+)/$',views.Dikko_Products_List.as_view(),name='dashboard_dikko_products_list_remove'),
    re_path('dikko_management/edit/products_list/(?P<pk>\d+)/$',views.Dikko_Products_List.as_view(),name='dashboard_dikko_products_list_edit'),
    path('dikko_management/pre_add',views.Dikko_Info_List.as_view(),name='dashboard_dikko_pre_add'),
    path('dikko_management/pre_remove',views.Dikko_Info_List.as_view(),name='dashboard_dikko_pre_remove'),
    path('dikko_management/pre_edit',views.Dikko_Info_List.as_view(),name='dashboard_dikko_pre_edit'),
    re_path(r'dikko_management/add_product/(?P<pk>\d+)/$',views.Dikko_Add_Product.as_view(),name='dashboard_dikko_management_add_product'),
    re_path(r'dikko_management/edit_product/(?P<pk>\d+)/(?P<pro>\d+)$',views.Dikko_Edit_Product,name='dashboard_dikko_management_edit_product'),
    re_path(r'dikko_management/remove_product/(?P<pk>\d+)/(?P<pro>\d+)$',views.Dikko_Remove_Product.as_view(),name='dashboard_dikko_management_remove_product'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),
    path('ajax/load-fields/', views.load_fields, name='ajax_load_fields'),
    path('orders/',views.dashboard_orders.as_view(),name='dashboard_orders'),
    path('notifications/create', views.create_notification, name='dashboard_notifications_create'),
    path('notifications/list', views.Notifications_List.as_view(), name='dashboard_notifications_list'),
    path('notifications/orders',views.notifications_orders_list,name='dashboard_notifications_orders'),
    path('notifications/comments',views.notifications_comments_list,name='dashboard_notifications_comments'),
    re_path(r'^notifications/orders/details/(?P<pk>\d+)/$',views.notifications_orders_details.as_view(),name='dashboard_notifications_orders_details'),
    path('dicount_codes/',discount_views.Create_Code.as_view(),name='dashboard_discount_codes'),
    path('favorite_list/',favorite_views.Favorite_List.as_view(),name='dashboard_favorite_list'),
    path('analytics/',analytics_views.home.as_view(),name='dashboard_analytics'),
    path('analytics/sell_per_product',analytics_views.sell_per_product,name='dashboard_analytics_sell_per_product'),
    path('analytics/sell_per_dikko', analytics_views.sell_per_dikko, name='dashboard_analytics_sell_per_dikko'),
    path('subscribers/', subscribers_views.communityList, name='dashboard_subscribers_communities'),
    re_path(r'^subscribers/community/(?P<slug>[\w-]+)/create_message/$', subscribers_views.createMessage, name='dashboard_subscribers_create_message'),
    re_path(r'^subscribers/community/(?P<slug>[\w-]+)/message_list/$', subscribers_views.messagesList, name='dashboard_subscribers_message_list'),
    re_path(r'^subscribers/community/(?P<slug>[\w-]+)/message_details/(?P<message>[\w-]+)$', subscribers_views.messageDetail, name='dashboard_subscribers_message_details'),
    path('complains/', complain_views.complainList, name='dashboard_complains_list'),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
import datetime
from xml.dom import minidom

import requests
from django.http import JsonResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import TemplateView, UpdateView, ListView, CreateView, DetailView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from jalali_date import datetime2jalali

from products.models import Product, Dress, CImage, get_upload_path, Zivar,RuDuzi,Dast_Saze
# from django.contrib.auth.models import User
from django.views.generic.edit import FormMixin
from comments.models import Comment
from accounts.models import User
from .forms import info_form, info_form_user, info_dikko_form, add_product, create_dikko, \
    address_form, create_notif, add_dress, add_zivar, add_ruDuzi,add_DastSaze_Honari
from accounts.models import Profile, Seller_Profile, City, Address, Reciever
from dikko.models import Dikko, Sub_Field, Field
from notif.models import Notification
from orders.models import Order
from django.conf import settings
import os
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from dikko2.utils import unique_product_code_generator
from .email import send_email


# User = get_user_model()
# Create your views here.
class AdminStaffRequiredMixin(LoginRequiredMixin, UserPassesTestMixin):

    def test_func(self):
        return self.request.user.is_admin


@login_required
def dashboard_account_information(request):
    instance=Profile.objects.get(user=request.user)
    user=User.objects.get(email=request.user.email)
    user_form=info_form_user(request.POST or None, instance=user)
    form=info_form(request.POST or None, instance=instance)
    addre_form=address_form()
    address=instance.address_set.all()
    print(address)
    success=False
    if request.method=='POST':
        print("helooo")
        if form.is_valid():
            form.save()
        if user_form.is_valid():
            user_form.save()
            success=True
        else:
            print(form.errors)
            print(user_form.errors)
    return render(request, 'dashboard-personalInformation.html',
                  {'form': form, 'profile': instance, 'user_form': user_form, 'address': address, 'success': success,
                   'address_form': addre_form})


class Dikko_Info_List(AdminStaffRequiredMixin, ListView):
    template_name='dashboard-dikko-info.html'
    model=Dikko
    queryset=Dikko.objects.all()
    paginate_by=8

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        profile=Profile.objects.get(user=self.request.user)
        context['profile']=profile
        return context


class Dikko_Products_List(AdminStaffRequiredMixin, ListView):
    template_name='dashboard-dikko-products-list.html'
    paginate_by=8

    def get_queryset(self):
        dikko_pk=self.kwargs.get('pk')
        dikko=Dikko.objects.get(pk=dikko_pk)
        return dikko.products.all()

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        profile=Profile.objects.get(user=self.request.user)
        context['profile']=profile
        dikko_pk=self.kwargs.get('pk')
        dikko=Dikko.objects.get(pk=dikko_pk)
        context['dikko']=dikko
        return context


class Dikko_Info_Details(AdminStaffRequiredMixin, UpdateView):
    template_name='dashboard-dikko-info-details.html'
    model=Dikko
    form_class=info_dikko_form

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        profile=Profile.objects.get(user=self.request.user)
        context['profile']=profile
        return context

    def get_success_url(self):
        return reverse('dashboard:dashboard_dikko_info')


class Dikko_Add_Product(AdminStaffRequiredMixin, DetailView):
    model=Product
    template_name='dashboard-dikko-management-add-product.html'

    # form_class = add_product
    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        profile=Profile.objects.get(user=self.request.user)
        context['profile']=profile
        dikko=self.get_object()
        sfileds=dikko.sfield.all()
        dress=False
        zivar=False
        for sfield in sfileds:
            if sfield.scode[0]=='D':
                if sfield.scode[1]=='H':
                    context['another_form']=add_DastSaze_Honari()
                else:
                    dress_form=add_dress()
                    context['another_form']=dress_form

            elif sfield.scode[0]=='H':
                if sfield.scode[1]=='J':  ### zivarAlat
                    zivar_form=add_zivar()
                    context['another_form']=zivar_form
                elif sfield.scode[1]=='R':  # RuDUzi
                    ruDuzi=add_ruDuzi()
                    context['another_form']=ruDuzi
            elif sfield.scode[0]=='A':  # Agricuture
                pass

        return context

    def post(self, request, *args, **kwargs):
        self.object=self.get_object()

        # another_form=add_dress(self.request.POST,prefix='another_form')
        print("HIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII")
        dikko=self.get_object()
        sfileds=dikko.sfield.all()
        another_form=None
        for sfield in sfileds:
            if sfield.scode[0]=='D':
                if sfield.scode[1]=='H':
                    another_form=add_DastSaze_Honari(self.request.POST)
                else:
                    another_form=add_dress(self.request.POST)
                    print("ANOTHERRRRRRRRRRRRR")
                    print(another_form)
            elif sfield.scode[0]=='H':
                if sfield.scode[1]=='J':  ### zivarAlat
                    another_form=add_zivar(self.request.POST)
                elif sfield.scode[1]=='R':
                    another_form=add_ruDuzi(self.request.POST)
        # print(self.form_class)
        # print(self.get_form_class())
        # print(self.get_form())
        dirname=self.object.name
        dir=settings.MEDIA_ROOT
        print(dir)
        product_dir=os.path.join(dir, 'products')
        image_dir=os.path.join(product_dir, 'img')
        seller_dir=os.path.join(image_dir, dirname)
        if not os.path.isdir(seller_dir):
            os.mkdir(seller_dir)
        print(self.request.POST)
        print(another_form.errors)
        if another_form.is_valid():

            kwargs={'another_form': another_form}
            return self.form_valid(another_form)

        else:
            print("NOTTTT VALID")
            return self.render_to_response(self.get_context_data())

    def form_valid(self, form):

        new_p=form.save()
        profile=Profile.objects.filter(seller_profile=self.get_object().owner).first()
        print(self.request.FILES)
        new_p.seller=profile
        new_p.dikko_name=self.get_object().name
        new_p.dikko_slug=self.get_object().slug
        new_p.code=unique_product_code_generator(new_p, self.get_object())

        new_p.save()
        # form.save()
        new_p.save()
        for afile in self.request.FILES.getlist('files'):
            image=afile

            path='products/img/{0}/{1}/{2}'.format(new_p.dikko_name, new_p.title, image)
            ci=CImage()
            ci.path=path
            ci.save()

            ci.image=image
            ci.save()
            new_p.image.add(ci)
            new_p.save()

        if isinstance(new_p, Dress):
            print(new_p.color.all())
            print(new_p.price)

        self.get_object().products.add(new_p)
        return redirect('dashboard:dashboard_dikko_pre_add')

    def get_object(self, *args, **kwargs):
        request=self.request
        pk=self.kwargs.get('pk')
        try:
            instance=Dikko.objects.get(pk=pk)
            print(instance.name)
        except Product.DoesNotExist:
            raise Http404("Not Found..")

        return instance

    def get_success_url(self):
        pk=self.kwargs.get('pk')
        return reverse('dashboard:dashboard_dikko_management_add_product', kwargs={'pk': pk})


class Dikko_Remove_Product(AdminStaffRequiredMixin, DeleteView):
    model=Product
    template_name='dashboard-delete-product.html'

    def get_object(self, queryset=None):
        request=self.request
        pk=self.kwargs.get('pk')
        pk2=self.kwargs.get('pro')
        try:
            pro=Product.objects.get(pk=pk2)
            instance=Dikko.objects.get(pk=pk)
            print(instance.name)
        except Product.DoesNotExist:
            raise Http404("Not Found..")

        return pro

    def get_success_url(self):
        pk=self.kwargs.get('pk')
        return reverse('dashboard:dashboard_dikko_products_list_remove', kwargs={'pk': pk})


@login_required
def Dikko_Edit_Product(request, pk, pro):
    dikko=Dikko.objects.get(pk=pk)
    sfileds=dikko.sfield.all()
    form=None
    for sfield in sfileds:
        if sfield.scode[0]=='D':
            if sfield.scode[1]=='H':
                dast_saze=Dast_Saze.objects.get(pk=pro)
                form=add_DastSaze_Honari(request.POST or None,instance=dast_saze)
            else:
                dress=Dress.objects.get(pk=pro)
                form=add_dress(request.POST or None, instance=dress)
        elif sfield.scode[0]=='H':
            if sfield.scode[1]=='J':
                zivar=Zivar.objects.get(pk=pro)
                form=add_zivar(request.POST or None, instance=zivar)
            elif sfield.scode[1]=='R':
                ruduzi=RuDuzi.objects.get(pk=pro)
                form=add_ruDuzi(request.POST or None , instance=ruduzi)

    if request.POST:
        if form.is_valid():
            new_p=form.save(commit=False)
            new_p.code=unique_product_code_generator(new_p, dikko)
            new_p.save()
            form.save_m2m()
            new_p.save()

dashboard/templates/dashboard-create-notification.html
{% extends 'dashboard.html' %}
{% block dashboard %}
<div class="container" >
{% if request.user.is_staff %}

				<div class="row">
					<!-- sidebar-area start-->

					<!-- sidebar-area end-->
					<div class="col-lg-9 col-md-8 col-xs-12">
						<div class="blog-details-wrap mb-20">
                            <form method="post">
                                {% csrf_token %}
                                {{ form.verb }}
                                <button class="btn btn-primary btn-lg full-width" type="submit">ثبت تغییرات</button>
                            </form>

                        </div>
                    </div>
                </div>
{% endif %}
</div>
{% endblock %}

dashboard/templates/dashboard-delete-address.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

dashboard/templates/dashboard-dikko-management-add-product.html
{% extends 'dashboard.html' %}
{% load static %}
{% block dashboard %}

    {{ another_form.media }}
    {#    <div class="main ptb-50 bg-2">#}
    <!-- blog-details-area start -->
    {#		<div class="blog-details-area bg-2 ptb-70">#}
    <div class="container">
        <div class="row">
            <!-- sidebar-area start-->

            <!-- sidebar-area end-->
            <div class="col-lg-9 col-md-8 col-xs-12">
                <div class="ui-block">
                    <div class="blog-details-wrap mb-20">
                        {{ another_form.errors }}
                        {% if user.staff %}
                            <form method="post" enctype="multipart/form-data">
                                {#                                     <div class="modal-body mx-3">#}

                                {% csrf_token %}
                                {#                                            <div class="form-group label-floating">#}
                                {#									            <label class="control-label">نام محصول</label>#}
                                {#									            {{ form.title }}#}
                                {##}
                                {#								            </div>#}
                                {#                                            <div class="form-group label-floating">#}
                                {#									            <label class="control-label">توضیحات</label>#}
                                {#									            {{ form.description }}#}
                                {#								            </div>#}
                                {#                                            <div class="form-group label-floating">#}
                                {#                                                <label class="control-label">قیمت محصول</label>#}
                                {#                                                {{ form.price }}#}
                                {#                                            </div>#}
                                {#                                            <div class="form-group label-floating">#}
                                {#									            <label class="control-label">عکس محصول</label>#}
                                {#									            {{ form.image }}#}
                                {#								            </div>#}
                                {#                                            <div class="form-group label-floating">#}
                                {#									            <label class="control-label">2عکس محصول</label>#}
                                {#									            {{ form.image2 }}#}
                                {#								            </div>#}
                                {#                                            <div class="form-group label-floating">#}
                                {#									            <label class="control-label">3عکس محصول</label>#}
                                {#									            {{ form.image3 }}#}
                                {#								            </div>#}
                                {#                                            <div class="form-group label-floating">#}
                                {#									            <label class="control-label">4عکس محصول</label>#}
                                {#									            {{ form.image4 }}#}
                                {#								            </div>#}
                                <div class="row">
                                    <div class="col col-md-12">
                              <div class="form-group ">
                                            <label class="control-label">  {{ another_form.title.label }}</label>

                                            {{ another_form.title }}
                                        </div>
                                        <div class="form-group ">
                                            <label class="control-label">{{ another_form.description.label }}</label>

                                            {{ another_form.description }}
                                        </div>
                                        <div class="form-group ">
                                            <label class="control-label">عکس ها</label>

                                            <input name="files" type="file" size="50" accept="image/*" multiple>
                                        </div>


                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col col-lg-6 col-md-6 col-sm-12 col-12">


                                    </div>
                                    {% for item in another_form %}
                                        {% if item.name != 'title' and item.name != 'description' and item.name != 'image' %}
                                            {#                                            {{ item }}#}
                                            {#                                         {% if item.count > 0 %}#}

                                            {#                                             {% else %}#}
                                            <div class="col-md-6">
                                                <div class="form-group ">
                                                    <label class="control-label">{{ item.label }}</label>

                                                    {{ item }}
                                                </div>
                                            </div>
                                            {#                                        {% endif %}#}
                                        {% endif %}




                                        {#                                        {% for i in item %}#}
                                        {#                                            <div class="col-md-9">#}
                                        {##}
                                        {##}
                                        {##}
                                        {#                                            	<input type="checkbox" name="check" checked> <span class="label-text">{{ i }}</span>#}
                                        {#                                            </div>#}
                                        {#                                        {% endfor %}#}




                                    {% endfor %}


                                </div>


                                {#                                           <div class="form-group label-floating">#}
                                {#									            <label class="control-label">تگ ها</label>#}
                                {#									            {{ form.tags }}#}
                                {#								            </div>#}


                                {#                                     </div>#}
                                <div class="modal-footer d-flex justify-content-center">
                                    <input type="hidden" value="charm2" name="hidden_input">
                                    <button class="btn btn-default" type="submit">ثبت</button>
                                </div>
                            </form>
                        {% endif %}


                    </div>
                </div>
            </div>
        </div>
    </div>
    {#		</div>#}
    {#    </div>#}
    <!-- blog-details-area end -->
{% endblock %}
<!-- newsletter-area start -->

dashboard/templates/dashboard-dikko-management.html
{% extends 'dashboard.html' %}

{% block dashboard %}
{#    <div class="main ptb-50">#}
		<!-- blog-details-area start -->
{#		<div class="blog-details-area bg-2 ptb-70">#}
			<div class="container" >
				<div class="row">
					<!-- sidebar-area start-->

					<!-- sidebar-area end-->
					<div class="col-lg-9 col-md-8 col-xs-12">
						<div class="blog-details-wrap mb-20">
                            <div class="row">
                                <div class="col col-lg-6 col-md-6 col-sm-12 col-12">
                                <p>مدیریت دیکو</p>


                                </div>
                            </div>






						</div>

					</div>
				</div>
			</div>
{#		</div>#}
{#    </div>#}
		<!-- blog-details-area end -->
{% endblock %}
		<!-- newsletter-area start -->

dashboard/templates/dashboard-dikko-pre-add.html
{% extends 'dashboard.html' %}
{% block dashboard %}
{#    <div class="main ptb-50 bg-2">#}
		<!-- blog-details-area start -->
{#		<div class="blog-details-area bg-2 ptb-70">#}
			<div class="container" >
				<div class="row">
					<!-- sidebar-area start-->

					<!-- sidebar-area end-->
					<div class="col-lg-9 col-md-8 col-xs-12">
						<div class="blog-details-wrap mb-20">
                            {% if user.staff %}
                                {% if request.path == "/dashboard/dikko_management/" %}
                                    {% for dikko in object_list %}
                                      <a href="{% url 'dashboard:dashboard_dikko_management_add_product' pk=dikko.pk %}"> <button class="btn btn primary" >{{ dikko }}</button></a>
                                    {% endfor %}
                                    <a href="{% url 'dashboard:dashboard_dikko_management_remove_product'  pk=17 pro=47 %}"> <button class="btn btn primary" >حذف</button></a>
                                    {% else %}


                                    {% for dikko in object_list %}
                                      <a href="{% url 'dashboard:dashboard_dikko_info_details' pk=dikko.pk %}"> <button class="btn btn primary" >{{ dikko }}</button></a>
                                    {% endfor %}
                                {% endif %}
                            {% endif %}





						</div>

					</div>
				</div>
			</div>
{#		</div>#}
{#    </div>#}
		<!-- blog-details-area end -->
{% endblock %}
		<!-- newsletter-area start -->

dashboard/templates/dashboard-dikko-products-list.html
{% extends 'dashboard.html' %}
{% block dashboard %}
    {#    <div class="main ptb-50 bg-2">#}
    <!-- blog-details-area start -->
    {#		<div class="blog-details-area bg-2 ptb-70">#}
    <div class="container">
        <div class="row">
            <!-- sidebar-area start-->

            <!-- sidebar-area end-->
            <div class="col-lg-9 col-md-8 col-xs-12">
                <div class="ui-block">
                    {% if user.staff %}

                        {% if "remove" in request.path %}
                            <div class="ui-block-title">
                                <h4 class="title">محصول برای حذف را انتخاب کنید</h4>
                                <a href="#" class="more">
                                    <svg class="olymp-three-dots-icon">
                                        <use xlink:href="svg-icons/sprites/icons.svg#olymp-three-dots-icon"></use>
                                    </svg>
                                </a>
                            </div>
                            <ul class="notification-list">
                                {% for obj in object_list %}
                                    <li>
                                        <div class="author-thumb">
                                            <img src="{{ obj.image.all.first.image.url }}" alt="product">
                                        </div>
                                        <div class="notification-event">
                                            <a href="{% url 'dashboard:dashboard_dikko_management_remove_product' pk=dikko.pk pro=obj.pk %}"
                                               class="h6 notification-friend">{{ obj }}</a>


                                        </div>
                                    </li>
                                {% endfor %}

                            </ul>

                        {% else %}
                            <div class="ui-block-title">
                                <h4 class="title">محصول برای ویرایش را انتخاب کنید</h4>
                                <a href="#" class="more">
                                    <svg class="olymp-three-dots-icon">
                                        <use xlink:href="svg-icons/sprites/icons.svg#olymp-three-dots-icon"></use>
                                    </svg>
                                </a>
                            </div>
                            <ul class="notification-list">
                                {% for obj in object_list %}
                                    <li>
                                        <div class="author-thumb">
                                            <img src="{{ obj.image.all.first.image.url }}" alt="author">
                                        </div>
                                        <div class="notification-event">
                                            <a href="{% url 'dashboard:dashboard_dikko_management_edit_product' pk=dikko.pk pro=obj.pk %}"
                                               class="h6 notification-friend">{{ obj }}</a>


                                        </div>
                                    </li>
                                {% endfor %}

                            </ul>




                        {% endif %}

                    {% endif %}


                </div>

            </div>
        </div>
    </div>
    {#		</div>#}
    {#    </div>#}
    <!-- blog-details-area end -->
{% endblock %}
<!-- newsletter-area start -->

dashboard/templates/fields-select-list.html
<option value="" class="dropdown-menu">---------</option>
{% for sfield in sfields %}
    {% for s in sfield %}
        <option value="{{ s.pk }}">{{ s.name }}</option>
        {% endfor %}

{% endfor %}